Public organization mediafiles
OpenSlides/openslides-autoupdate-service pull request #1000
Opened 2024-08-30 10:29 UTC by bastianjoel

2024-09-04 12:59 UTC, bastianjoel commented
Discussed with @emanuelschuetze that orga mediafiles should require can manage organization permissions.

2024-09-05 07:32 UTC, ostcar requested changes
I could only review the code but not, if it is doing the correct thing.

Please first update the Docstring above Mediafile and MeetingMediafile so I can see, how it should behave. Then I can review it again.

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/organization.go
> +func (Organization) modeE(ctx context.Context, ds *dsfetch.Fetch, ids ...int) ([]int, error) {
Please add a test for the new modeE

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/organization.go
> +	if err != nil || !isAdmin {
Please do this in two steps. I understand, that it works, but it is not clear on the first view, that in the condition block, error can be nil, so the condition ins not only in error casses.

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +				managementLevel, err := perm.HasOrganizationManagementLevel(ctx, ds, requestUser, perm.OMLCanManageOrganization)
In line 13 to line 27 is the documentation of the collection.  This probably also has to change.

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +					return nil, err
Please add a new error string like `return nil, fmt.Errorf("....: %w", err)

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +			token, err := ds.Mediafile_Token(mediafileID).Value(ctx)
Please add an error string in in line 94

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +			if token != "" {
Are you sure, you don't have to check the token?

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +				return false, err
Please add an error string

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +			if val, isSet := published.Value(); isSet && val == 1 {
I think, I would have written: `if val, _ := published.Value(); val == 1`. If isSet is false, then val is always 0. But maybe your solution is more clear.

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +					return false, err
Please add an error string

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +				return requestUser != 0, nil
This is complicated to read. There are a lot of conditions here, that are in different lines.

It returns true here, if requestUser is not 0, and collection == "organization" and it is not published or it is published, but the value is not 1.

Could you restructure the code, so the different conditions get more clear? I think a switch statement could help

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +				return false, err
Please add an error string

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +				canSeeMeetingMediafile, err := Collection(ctx, MeetingMediafile{}.Name()).Modes("A")(ctx, ds, meetingMediafileIDs...)
With this call, Mediafile depends on MeetingMediaFile. So you have to make sure, that MeetingMediaFile is above Mediafile in restrict.go line 582. This makes sure, MeetingMediaFileIDs are called before Mediafile, so the caching works.

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +// MeetingMediafile handels permissions for the collection mediafile.
It seems, that this is a copy and paste of the Mediafile. Could you check this? For example, what is a MeetingMediafile, that belongs to an organization

2024-09-05 07:32 UTC, ostcar commented on internal/restrict/restrict.go
> +	"meeting_mediafile":                46,
This probably has to be above mediafile (currently on 9). See above

2024-09-05 09:13 UTC, bastianjoel commented on internal/restrict/collection/mediafile.go
> +			if token != "" {
In https://github.com/OpenSlides/OpenSlides/wiki/Mediafiles#organization-wide-mediafiles it is documented that a file should be public with any token.

2024-09-05 09:15 UTC, bastianjoel commented on internal/restrict/collection/mediafile.go
> +				managementLevel, err := perm.HasOrganizationManagementLevel(ctx, ds, requestUser, perm.OMLCanManageOrganization)
The specifications changed here.

2024-09-05 09:21 UTC, bastianjoel commented on internal/restrict/collection/mediafile.go
> +				return requestUser != 0, nil
This got a bit simpler now with a specification change.

2024-09-09 07:51 UTC, ostcar requested changes

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +//	The user is an admin of the meeting.
I think this can be removed. An admin of a meeting automaticity has `mediafile.can_manage`, so this rule is redundant.

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +//	The user has projector.can_see and there exists a meeting_mediafile/projection_ids with projection/current_projector_id set.
Could you change this sentence? It seems wrong. I think what you mean is:
```
The user has projector.can_see and one of the projections linked with meeting_mediafile/projection_ids has projection/current_projector_id set.
```

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +		if perms.IsAdmin() {
This can be changed with
```
if perms.Has(perm.MediafileCanManage) {
    return ids, nil
}
```

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +			if perms.Has(perm.MediafileCanManage) {
This is not needed, if you change the `isAdmin` before the loop

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +		canSeeMeeting, err := Collection(ctx, Meeting{}.Name()).Modes("B")(ctx, ds, meetingID)
You can use this as an early escape. In the user can not see a meeting, then non of the rules above match.

So you can add a `if !canSeeMeeting { return nil, nil}`

This should be at the top of the `eachMeeting`

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +			if len(canSeeMeeting) == 1 && logoOrFont {
When you add the early escape of `canSeeMeeting` above, then you don't need the condition here.

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +//	    The user has groups in common with meeting_mediafile/inherited_access_group_ids.
This is not a full sentence. The `The` at the beginning has to be lowercase.

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +					if perms.InGroup(id) {
I don't like this loop. `eachCondition` loops throw all mediafile_ids. then there is the loop over inheritedGroups and inside of `perms.InGroup` there is a loop over the groups of the user. So this is O(n^3). Maybe change [pers.InGroup](https://github.com/OpenSlides/openslides-autoupdate-service/blob/fd44caacbd50854f4fb7f9ac7c8c4be874cba4b7/internal/restrict/perm/perm.go#L171-L186) to:
```go
func (p *Permission) InGroup(groupIDs ...int) bool {
	if p == nil {
		return false
	}

	if p.admin {
		return true
	}

        for_, gid := range groupIDs {
	    for _, id := range p.groupIDs {
		    if id == gid {
			return true
		    }
             }
	}
	return false
}
```
Then it is still O(N^3) but at least the two conditions only are checked once per mediafile*inheritedGroups (which still is too many times, but at least...)

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +//	The meeting mediafile belongs to the organization and the user has organization management permissions
Would the statement be true, that with organization management permissions, you can see all `mediafiles`, even when they belong to a meeting? If this is true, the code could be more optimized.

But I am not sure, since the organization-manager could be looked out of the meeting.

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +				managementLevel, err := perm.HasOrganizationManagementLevel(ctx, ds, requestUser, perm.OMLCanManageOrganization)
Please move this before the `eachContentObjectCollection`. The variable `managementLevel` is the same for each. So it can be calculated only once.

Then you canchange line 73 from `if collection == "organization" {` to `if collection == "organization" && managementLevel {` (you could also rename `managementLevel` to `hasManagementLevel`)

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +				isAdmin, err := isMeetingAdmin(ctx, ds)
Please move this check at the top of the function. `isMeetingAdmin` should only be called once, and not once per mediafile.

Then you can also change the condition in line 101 from `val == 1 && isAdmin`

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +			if val, _ := published.Value(); val == 1 {
I think this reads strange. Maybe `if !published.Null()` is nicer?

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +			} else if collection == "organization" {
I still think, that an explicit

`if collection == "organization" && (!published.Null() || isAdmin) {` 

is easier to read

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +			if len(meetingMediafileIDs) > 0 {
I am not sure if this condition is needed. I think it should work without. A call to `Collection(ctx, MeetingMediafile{}.Name()).Modes("A")(ctx, ds, meetingMediafileIDs...)` with an empty list of meetingMediafileIDs should return an empty list of ids, so `if len(canSeeMeetingMediafile) >= 1 {` is still correct.

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/collection/mediafile.go
> +func isMeetingAdmin(ctx context.Context, ds *dsfetch.Fetch) (bool, error) {
The name is unclear. When I first read it, I though "which meeting?". Could you change it to something like `isAdminInAnyMeeting`? Or is this too long for an unexported function?

If you keep the name, could you at leat add a short doc-comment, that explains it?

2024-09-09 07:51 UTC, ostcar commented on internal/restrict/restrict.go
> +	"mediafile":                        10,
I am sorry. I should have used another system then a map[string]int. It is hard to change and not performant.
I don't know, why I did not use just a []string. But this is something for another PR :)

2024-09-09 07:53 UTC, ostcar requested changes

2024-09-09 07:53 UTC, ostcar commented on internal/restrict/collection/meeting_mediafile.go
> +				for _, id := range accessGroups {
If you change `perms.InGroup` as proposed in another comment, then you can use `perms.InGroup(accessGroups...)` here as well

2024-09-09 08:38 UTC, bastianjoel commented on internal/restrict/restrict.go
> +	"mediafile":                        10,
Its just `qa<Ctrl>+aqj35@a` in vim, so no big deal ;)

2024-09-09 09:13 UTC, bastianjoel commented on internal/restrict/collection/meeting_mediafile.go
> +				for _, id := range accessGroups {
I misread the documentation here. Access groups are not relevant.

2024-09-09 09:33 UTC, bastianjoel commented on internal/restrict/collection/meeting_mediafile.go
> +			if perms.Has(perm.MediafileCanManage) {
`MediafileCanManage` will not permit a user to access all mediafiles anymore.

2024-09-09 09:56 UTC, bastianjoel commented on internal/restrict/collection/meeting_mediafile.go
> +		if perms.IsAdmin() {
This is kept in favor of completely removing the `perm.MediafileCanManage` check.

2024-09-09 09:59 UTC, bastianjoel commented on internal/restrict/collection/meeting_mediafile.go
> +					if perms.InGroup(id) {
Also changed in some other places

2024-09-09 12:16 UTC, bastianjoel commented on internal/restrict/collection/mediafile.go
> +//	The meeting mediafile belongs to the organization and the user has organization management permissions
I am not exactly sure but I would guess no.

2024-09-09 13:59 UTC, ostcar approved these changes
Thank you

2024-09-10 07:46 UTC, merged