OIDC/Auth2 integration
OpenSlides/openslides-autoupdate-service pull request #1030
Opened 2024-09-27 09:06 UTC by boehlke

This PR contains a POC for a OIDC/oauth2 integration into OpenSlides. The dev setup is based on keycloak.

2024-10-11 10:27 UTC, bastianjoel commented
@boehlke There are linter errors. Could you fix this?

2024-10-15 08:20 UTC, bastianjoel commented
@boehlke Could you also have a look on the tests?

2025-01-14 16:59 UTC, ostcar requested changes
Please reask a review, when it is ready to merge

2025-02-08 12:08 UTC, ostcar commented
We moved the auth code to a separat go repository: https://github.com/OpenSlides/openslides-go

The code is exactly the same. But you have to recreate your PR on the new repo.

2025-02-08 12:08 UTC, closed without merging