Projector.service user slide
OpenSlides/openslides-autoupdate-service pull request #200
Opened 2021-04-30 14:28 UTC by r-peschke

Perhaps we should take 2 strategies to resolve the template fields:
- the implemented one reads all replacements
- in most cases there is only one replacement that we know, in most cases the meeting_id". We could use this as replacement without extra request to database and without appending the $-field to the list of keys.

2021-05-01 05:57 UTC, ostcar requested changes

2021-05-01 05:57 UTC, ostcar commented on internal/projector/slide/user.go
> +		parts = append(parts, fmt.Sprintf("(%s)", level))
I would do it like this:
```go
level := u.Level[meetingID]
if level == "" {
  level = u.DefaultLevel
}
if level != "" {
  parts = append(parts, fmt.Sprintf("(%s)", level)
}
```

2021-05-01 05:57 UTC, ostcar commented on internal/projector/slide/user_test.go
> +			emptySlice,
This is a bit strange. It is called `emptySlice` but it contains three elements. Maybe you should rename it

2021-05-01 05:57 UTC, ostcar commented on internal/projector/slide/user.go
> +	return []byte(fmt.Sprintf(`{"user":"%s"}`, u.String(p7on.MeetingID))), keys, nil
Maybe we have to rename `u.String()` to something else. When I read this, I thought the function would convert the MeetingID to a string.

2021-05-01 05:57 UTC, ostcar commented on internal/projector/slide/user_test.go
> +	assert.Contains(t, err.Error(), "Error encoding responceData `map[user:map[1:map[username:jonny123]]]`")
I don't understand why this should be an error. I thought this would return `{"user":"jonny123"}` Can you explain this to me.

2021-05-03 08:46 UTC, r-peschke commented on internal/projector/slide/user.go
> +		parts = append(parts, fmt.Sprintf("(%s)", level))
Done

2021-05-03 08:57 UTC, r-peschke commented on internal/projector/slide/user_test.go
> +			emptySlice,
Done. It's now addKeysExpected, equal to the related structure field.

2021-05-03 09:23 UTC, r-peschke commented on internal/projector/slide/user.go
> +	return []byte(fmt.Sprintf(`{"user":"%s"}`, u.String(p7on.MeetingID))), keys, nil
The name `String` was yours. I thought it's a kind of standard in Go to get a string representation of an instance.
Isn't there any standard for this? Do you have a better proposal that we could use as a kind of generic name?

2021-05-03 11:30 UTC, r-peschke commented on internal/projector/slide/user_test.go
> +	assert.Contains(t, err.Error(), "Error encoding responceData `map[user:map[1:map[username:jonny123]]]`")
The reason why it's raising the error are the missing  around the "jonny123"-data. I just wanted to produce an error for testing purposes.
Choose another more serious error: based on new specification in [wiki](https://github.com/OpenSlides/OpenSlides/wiki/Projector-System#user) if there isn't minimum one of username, firstName, lastName there is no output and we should raise an error.

2021-05-04 06:59 UTC, ostcar requested changes

2021-05-04 06:59 UTC, ostcar commented on internal/projector/slide/user.go
> +		} else {
I don't think this is necessary. Each user has a Username. If not, the database is corrupted.

2021-05-04 06:59 UTC, ostcar commented on internal/projector/slide/user.go
> +// Get Representation of the ContentObjectId and MeetingID from the Projection, assuming it's a User
Each doc-string in go should start with the name of the function: https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

For exported objects this is checked by the linter. But I think it should also be done for non exported objects.

2021-05-04 06:59 UTC, ostcar commented on internal/projector/slide/user.go
> +// Get instance representation of the user
The comment should start with `String `: https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

2021-05-04 06:59 UTC, ostcar commented on internal/projector/slide/list_of_speakers.go
> +		userRepr, err = user.String(meetingID)
You have to check for the error. And there is no need to define the variable userRepr. Please use:
```go
userRepr, err := user.String(meetingID)
if err != nil {
  return fmt.Errorf("building user representation: %w", err)
}
```

But as written in another comment, I would propose that user.String() does not return an error. The only case is, if the username does not exist and this is not possible.

2021-05-04 06:59 UTC, ostcar commented on internal/projector/slide/user.go
> +func (u dbUser) String(meetingID int) (string, error) {
The method `String() string` is special. It is defined in the standard package [fmt](https://golang.org/pkg/fmt/#Stringer). The method is called by `fmt.Print`. See: https://play.golang.org/p/XcVK-6EoY7S

But this only works if the signature of String has no arguments and only returns a string.

I know it was me who named the method and gave it the argument. But now I see, that it should be renamed. An alternative would be to find a way to remove the argument and the error-return value.

Do you have an idea for a good name or for a way to use the method without a meetingID?

2021-05-04 06:59 UTC, ostcar commented on internal/projector/slide/user.go
> +			fmt.Println("user.go L. 39 Errorreturn")
Please remove tihs debugging line

2021-05-04 06:59 UTC, ostcar commented on internal/projector/slide/user.go
> +	fmt.Println("user.go L. 34: Username:" + u.Username)
Please remove this debugging line

2021-05-04 06:59 UTC, ostcar commented on internal/projector/slide/user.go
> +	repr, err = u.String(p7on.MeetingID)
You do not need the define the varialbe repr use:

```go
repr, err := u.String(p7on.MeetingID)
```

2021-05-04 07:00 UTC, ostcar commented on internal/projector/slide/user.go
> +	return []byte(fmt.Sprintf(`{"user":"%s"}`, u.String(p7on.MeetingID))), keys, nil
I answered your question in another comment.

2021-05-04 07:09 UTC, ostcar commented on internal/projector/slide/user_test.go
> +	assert.Contains(t, err.Error(), "Error encoding responceData `map[user:map[1:map[username:jonny123]]]`")
I would not test the error string. I think the strings are for humans and the test should not fail if the string changes.

If you just want to test that an error happens, then you can check that error is not nil.

If you want to check for a specific error, you should check the error type. `error` is just an interface. Everything with a method `Error() string` can be an error. Most go developers create errors and export them: https://golang.org/src/net/http/server.go?s=64501:64553#L41

I don't line that the error-objects are varialbe (see [this blog post](https://dave.cheney.net/2016/04/07/constant-errors)). And I also don't like to export error objects. This creates unnecessary dependencies between packages. For this reason, I identify errors by methods. See https://github.com/OpenSlides/openslides-vote-service/blob/main/internal/backends/test/test.go#L43-L46

2021-05-04 07:10 UTC, ostcar commented
> Perhaps we should take 2 strategies to resolve the template fields:
> 
> * the implemented one reads all replacements
> * in most cases there is only one replacement that we know, in most cases the meeting_id". We could use this as replacement without extra request to database and without appending the $-field to the list of keys.
You are right. I try to solve this in a separate PR. I have an idea...

2021-05-04 15:55 UTC, r-peschke commented on internal/projector/slide/user_test.go
> +	assert.Contains(t, err.Error(), "Error encoding responceData `map[user:map[1:map[username:jonny123]]]`")
I'm using now an explicit interface for errors in slides-function. The error will be returned in the expected client format. okay, I expect Finn will agree. What do you think about this way?
The provoked error itself we can remove, because the username since some days is really required. 

About checking the error string I don't agree. We should always check it if there is no own type, constant etc. to identify. Otherwise the test may fail with a new error of the same class without being discovered.

2021-05-04 15:56 UTC, r-peschke commented on internal/projector/slide/user.go
> +		} else {
See above. We should remove it after having a correct error output.

2021-05-04 16:03 UTC, r-peschke commented on internal/projector/slide/user.go
> +// Get Representation of the ContentObjectId and MeetingID from the Projection, assuming it's a User
Done

2021-05-04 16:03 UTC, r-peschke commented on internal/projector/slide/user.go
> +// Get instance representation of the user
Done

2021-05-04 16:04 UTC, r-peschke commented on internal/projector/slide/list_of_speakers.go
> +		userRepr, err = user.String(meetingID)
Modified, user.String does not return an error anymore

2021-05-04 16:14 UTC, r-peschke commented on internal/projector/slide/user.go
> +func (u dbUser) String(meetingID int) (string, error) {
Changed the name to StringMeetingDependent.
IMO it is the best, because we need the meeting dependent structure-level for the user representation

2021-05-04 16:15 UTC, r-peschke commented on internal/projector/slide/user.go
> +			fmt.Println("user.go L. 39 Errorreturn")
done

2021-05-04 16:15 UTC, r-peschke commented on internal/projector/slide/user.go
> +	fmt.Println("user.go L. 34: Username:" + u.Username)
done

2021-05-04 16:15 UTC, r-peschke commented on internal/projector/slide/user.go
> +	repr, err = u.String(p7on.MeetingID)
done

2021-05-06 07:42 UTC, FinnStutzenstein commented
@ostcar A review regarding the errors would be appreciated

2021-05-06 11:34 UTC, ostcar approved these changes

2021-05-06 11:34 UTC, ostcar commented on internal/http/http.go
> +	var errSlidesError slidesErrorI
I don't like that the http package checks for the slide-error. I think at the border of the projector-app the error should be converted to a `ClientError`

But for me it is ok that you leave the code as it is. I can refactor it later

2021-05-06 15:36 UTC, r-peschke commented on internal/http/http.go
> +	var errSlidesError slidesErrorI
okay

2021-05-06 15:36 UTC, merged