not functional: Objects in fetch.go to test with agenda_item_list
OpenSlides/openslides-autoupdate-service pull request #206
Opened 2021-05-10 13:50 UTC by r-peschke

Still not working on reflection error in fetch.go Objects, line  329 with "reflect.Value.Addr of unaddressable value"

2021-05-10 14:23 UTC, ostcar commented
I don't like that the function to fetch a list of objects is a separate function. It should be possible to reuse the code. 

I also don't see that this new function is really necessary. You can fall fetch.Objects many times. The only difference is, that you get less database queries. But this should not be a problem, since all keys are in the cache after one user fetched them.

I know that I wrote the "Object" function. But I am not a fan of it. It is too match magic. I don't think we should do more of it.

2021-06-08 10:19 UTC, r-peschke commented
Slider for agenda_item_list works as expected with new datastore interface. One test for all possible data for this slide included.

2021-06-10 04:54 UTC, ostcar requested changes

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda.go
> +		return nil, fmt.Errorf("encoding agenda item data")
Please add the original error:
```
return nil, fmt.Errorf("encoding agenda item data: %w", err)
```

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda.go
> +		return nil, fmt.Errorf("encoding agenda item list data")
Please add the original error, see above.

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda.go
> +			return nil, nil, err
Please wrap the error so it is easier to find this line in a traceback:

```
  return nil, nil, fmt.Errorf("get agenda item from map: %w", err)
```

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda.go
> +			return nil, nil, err
Please wrap the error

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda.go
> +			return nil, nil, err
Please wrap the error

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda.go
> +			return nil, nil, err
Please wrap the error

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda.go
> +			data = fetch.Object(ctx, []string{"id", "item_number", "content_object_id", "meeting_id", "is_hidden", "is_internal", "level"}, fmt.Sprintf("agenda_item/%d", aiID))
You don't need `fmt.Sprintf`. Have a look at the signature of the `Object` function: https://github.com/OpenSlides/openslides-autoupdate-service/blob/d00dd3c5df681febcf19b2c7f7051048590e31db/pkg/datastore/fetch.go#L38

You can write `fetch.Object(ctx, []string{...}, "agenda_item/%d", aiID)`

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda.go
> +				return nil, nil, err
Please wrap the error. Also on all other places. I don't write it here again but make another review after to added all the error-wrapping.

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/agenda_test.go
> +					    "title_information": {
The indenting is wrong.

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/assignment.go
> +		return nil, fmt.Errorf("encoding assignment data")
Please wrap the original error.

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/motion.go
> +		return nil, fmt.Errorf("encoding motion data")
Please wrap the original error

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/motion.go
> +		return nil, fmt.Errorf("encoding motion data")
Please wrap the original error

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/topic.go
> +		return nil, fmt.Errorf("encoding topic data")
error wrapping

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slide/topic.go
> +func Topic(store *projector.SlideStore) { // , ds projector.Datastore
Please remove the comment.

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slides.go
> +type TitlerFunc func(ctx context.Context, fetch *datastore.Fetcher, fqid string, meeting_id int, value map[string]interface{}) (title map[string]interface{}, err error)
Please change the signature of this function

The return value should not be `map[string]interface{}`. This disables the type system of go. You only use some keys with specific types. Please only return this types. You can either use a struct with the types or return the three keys directly.

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slides.go
> +func (s *SlideStore) RegisterTitleFunc(collection string, f TitlerFunc) {
Please make the names for slides and title more similar. So either rename this to `AddTitleFunc` or rename the old function to `RegisterSlideFunc`

2021-06-10 04:54 UTC, ostcar commented on internal/projector/slides.go
> +func (s *SlideStore) GetTitleFunc(collection string) TitlerFunc {
Please make the name of this function and the body similar to `SlideStore.Get`

2021-06-10 04:54 UTC, ostcar commented on pkg/datastore/helper.go
> +	"reflect"
Please remove reflect

2021-06-10 09:58 UTC, FinnStutzenstein commented on internal/projector/projector.go
> +				bs = []byte(fmt.Sprintf(`{"error":"Error parsing slide %s: %v!"}`, fqfield, err))
Errors are not directly shown in the client. If a projection has an error, it is printed to the console and the slide is not shown. Sending the traceback to the client would be appreciated to quickly find errors indicated by the traceback, especially for finding the problem to get around it in live situations. It enormously helps finding small bugs in production to hotfix them.  Additionally, all errors should be printed to the commandline, too. Also there is nothing to hide in these messages: The traceback itself is public. The initial message (e.g. "motion/5 could not be found") should only contain data that would have been published if there was no error (except for relations - but the content is what matters) since every information the code queries is used somehow in the slide data, otherwise you may just not query it.

2021-06-10 11:47 UTC, r-peschke commented on internal/projector/projector.go
> +	Options         map[string]interface{} `json:"options"`
I don't understand this. With this change it's really complicate to set the value
agenda_test.go, L. 220 would be: 
`Options:         map[string]json.RawMessage{"only_main_items": []byte("true")},`
and to get agenda.go L. ~110 would be like:
```
			var omi bool
			if err = json.Unmarshal(p7on.Options["only_main_items"], &omi); err != nil {
				return nil, nil, err
			}
```
How could this be written better and in this way, what is it for?

2021-06-10 12:02 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +		return nil, fmt.Errorf("encoding agenda item data")
Done

2021-06-10 12:02 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +		return nil, fmt.Errorf("encoding agenda item list data")
Done

2021-06-10 12:03 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +			return nil, nil, err
Done

2021-06-10 12:03 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +			return nil, nil, err
Done

2021-06-10 12:03 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +			return nil, nil, err
Done

2021-06-10 12:03 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +			return nil, nil, err
Done

2021-06-10 12:08 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +			data = fetch.Object(ctx, []string{"id", "item_number", "content_object_id", "meeting_id", "is_hidden", "is_internal", "level"}, fmt.Sprintf("agenda_item/%d", aiID))
Done

2021-06-10 12:08 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +				return nil, nil, err
Done

2021-06-10 12:17 UTC, r-peschke commented on internal/projector/slide/agenda_test.go
> +					    "title_information": {
done

2021-06-10 12:19 UTC, r-peschke commented on internal/projector/slide/assignment.go
> +		return nil, fmt.Errorf("encoding assignment data")
done

2021-06-10 12:26 UTC, r-peschke commented on internal/projector/slide/motion.go
> +		return nil, fmt.Errorf("encoding motion data")
done

2021-06-10 12:26 UTC, r-peschke commented on internal/projector/slide/motion.go
> +		return nil, fmt.Errorf("encoding motion data")
done

2021-06-10 12:26 UTC, r-peschke commented on internal/projector/slide/motion.go
> +		return nil, fmt.Errorf("encoding motion data")
Done

2021-06-10 12:28 UTC, r-peschke commented on internal/projector/slide/topic.go
> +		return nil, fmt.Errorf("encoding topic data")
done

2021-06-10 12:29 UTC, r-peschke commented on internal/projector/slide/topic.go
> +func Topic(store *projector.SlideStore) { // , ds projector.Datastore
done

2021-06-10 13:05 UTC, r-peschke commented on internal/projector/slides.go
> +type TitlerFunc func(ctx context.Context, fetch *datastore.Fetcher, fqid string, meeting_id int, value map[string]interface{}) (title map[string]interface{}, err error)
What type should it have?
We should give always a json with only the fields for the specified collection back. Otherwise the client has no criteria to distinct, which values to show.

2021-06-10 13:10 UTC, r-peschke commented on pkg/datastore/helper.go
> +	"reflect"
File removed

2021-06-10 13:26 UTC, r-peschke commented on internal/projector/slides.go
> +func (s *SlideStore) GetTitleFunc(collection string) TitlerFunc {
I don't understand what you mean:
respect to the function name:
Which name do you expect? IMO, if we change something, we should change Get to GetSliderFunc,  because we have 2 kinds of functions to Get.

respect to body:
I think we should check whether the functions is registered for the collection, because it's meant to be extended. AgendaItem/content_object_id always expects a GetTitleInformation-function.

2021-06-10 13:35 UTC, r-peschke commented on internal/projector/slides.go
> +func (s *SlideStore) RegisterTitleFunc(collection string, f TitlerFunc) {
Renamed it to RegisterSlideFunc

2021-06-10 13:54 UTC, ostcar commented on internal/projector/projector.go
> +				bs = []byte(fmt.Sprintf(`{"error":"Error parsing slide %s: %v!"}`, fqfield, err))
It does not matter if the error is shown to the client. I don't want, that he can see it in the console or by manually accessing the url. I see this as an security issue and will not accept this change. For the quick fix, you have to look into the server logs.

2021-06-10 14:03 UTC, ostcar commented on internal/projector/projector.go
> +	Options         map[string]interface{} `json:"options"`
I had bad experience with `map[string]interface{}`. This is way I use json.RawMessage at all places. I don't want to introduce another style here. 

If you don't want to write the `[]byte` type in test, then you can write converters for example there is the [yaml-converter](https://github.com/OpenSlides/openslides-autoupdate-service/blob/d00dd3c5df681febcf19b2c7f7051048590e31db/pkg/dsmock/datastore_mock.go#L19). I also often use the type `map[string]string` and convert it to `map[string]json.RawMessage`. ([exampe](https://github.com/OpenSlides/openslides-autoupdate-service/blob/d00dd3c5df681febcf19b2c7f7051048590e31db/internal/autoupdate/feature_test.go#L15))

2021-06-10 14:06 UTC, ostcar commented on internal/projector/slides.go
> +type TitlerFunc func(ctx context.Context, fetch *datastore.Fetcher, fqid string, meeting_id int, value map[string]interface{}) (title map[string]interface{}, err error)
I though, you would convert it to a string. I understand now, that you return it as a json-object. Maybe the client developers have to say what fields they need.

@FinnStutzenstein It is the function to show the title of an agenda item.

2021-06-10 14:14 UTC, ostcar commented on internal/projector/slides.go
> +func (s *SlideStore) GetTitleFunc(collection string) TitlerFunc {
Yes. This sounds good. Please do this.

2021-06-10 16:37 UTC, r-peschke commented on internal/projector/slides.go
> +type TitlerFunc func(ctx context.Context, fetch *datastore.Fetcher, fqid string, meeting_id int, value map[string]interface{}) (title map[string]interface{}, err error)
Not the only, but the most expandable usage of the title information function, is the agenda item list. Each agenda item has a content_object_id and it is it's title, that will be shown. See [here](https://github.com/OpenSlides/OpenSlides/wiki/Projector-System#get_title_informationfqid-meeting_id) the existing collections with getTitleInformation-requirements and their collection-specific content.
I think this is a classical schema to use map[string]interface{} and I would prefer this way:-)

To get it more your way, we could use a pattern with a type struct {type: string, data: json.RawMessage} and could create structs for the individual types, you may see [here](https://www.programmersought.com/article/23385788140/) a small example. Is this an acceptable way to handle this case?

2021-06-10 16:55 UTC, r-peschke commented on internal/projector/slides.go
> +func (s *SlideStore) GetTitleFunc(collection string) TitlerFunc {
Replaced the Get-Function by GetSliderFunc

2021-06-10 17:01 UTC, r-peschke commented on internal/projector/projector.go
> +				bs = []byte(fmt.Sprintf(`{"error":"Error parsing slide %s: %v!"}`, fqfield, err))
I don't think we will create an security issue with this. There is no data involved as @FinnStutzenstein  wrote.

But anywhere, we need a solution. We have to inform the client about the fact that there has been an error, problem or anything else as a reason to not display the content of the projection. What kind of error message we could sent, @ostcar? A special error type to check for or what do you propose?

2021-06-11 10:40 UTC, r-peschke commented on internal/projector/projector.go
> +	Options         map[string]interface{} `json:"options"`
I don't wanted to code it with map[string]json.RawMessage, but used a specific type for the options field.

2021-06-11 13:10 UTC, ostcar commented on internal/projector/projector.go
> +				bs = []byte(fmt.Sprintf(`{"error":"Error parsing slide %s: %v!"}`, fqfield, err))
The data is not sent to the user who activated the slide, but to the user who is looking at it. This user can not fix it. If you activate a slide that does not exist, there should be an error message from the backend and not the autoupdate.

2021-06-11 13:12 UTC, ostcar commented on internal/projector/projector.go
> +	Options         map[string]interface{} `json:"options"`
Then ping me at the places where the option is used and I code it.

2021-06-11 13:40 UTC, ostcar commented on internal/projector/slides.go
> +type TitlerFunc func(ctx context.Context, fetch *datastore.Fetcher, fqid string, meeting_id int, value map[string]interface{}) (title map[string]interface{}, err error)
What I don't like of the interface{} is, that you skip the go-type system. I would prefer if we define specific fields with specific types. I asked @FinnStutzenstein in a mail.

2021-06-14 06:15 UTC, FinnStutzenstein commented on internal/projector/slides.go
> +type TitlerFunc func(ctx context.Context, fetch *datastore.Fetcher, fqid string, meeting_id int, value map[string]interface{}) (title map[string]interface{}, err error)
Generics would be the solution; works fine in the client (typescript) for exactly this type of problem ;)

2021-06-14 07:48 UTC, r-peschke commented on internal/projector/projector.go
> +	Options         map[string]interface{} `json:"options"`
I think this is solved with the explicite type ProjectionOptions

2021-06-16 15:52 UTC, r-peschke commented on internal/projector/projector.go
> +				bs = []byte(fmt.Sprintf(`{"error":"Error parsing slide %s: %v!"}`, fqfield, err))
Changed. Instead the slide data, we send now something like  `{"error":"Error parsing slide projection/5/content!"}`

2021-06-17 13:58 UTC, r-peschke commented on internal/projector/slides.go
> +type TitlerFunc func(ctx context.Context, fetch *datastore.Fetcher, fqid string, meeting_id int, value map[string]interface{}) (title map[string]interface{}, err error)
I will change the return type of the GetTitleFunction from interface{} to a TitlerFuncResult-struct with specific fields. Marshaling is made with an omitempty, which omits the not used entries depending the type of colletion.

2021-06-17 14:09 UTC, ostcar commented on .gitignore
> +__debug_bin
Please add a newline

2021-06-17 14:10 UTC, ostcar commented on internal/projector/projector.go
> +				bs = []byte(fmt.Sprintf(`{"error":"Error parsing slide %s!"}`, fqfield))
fqfield is not the name of the slide but something like "projection/1/content". I don't see how this message would help, but it also does no harm. If you need it, it is ok for me.

2021-06-17 14:11 UTC, ostcar commented on internal/projector/projector.go
> +			return bs, err
Please revert that change or explain to me, why you think that it is necessary.

2021-06-17 15:05 UTC, r-peschke commented on .gitignore
> +__debug_bin
done

2021-06-17 15:06 UTC, r-peschke commented on internal/projector/projector.go
> +				bs = []byte(fmt.Sprintf(`{"error":"Error parsing slide %s!"}`, fqfield))
It is not the name of the slide, but it is the origin data of the requested slide.

2021-06-17 15:44 UTC, r-peschke commented on internal/projector/projector.go
> +			return bs, err
This is made in conjunction with the defer function, which changes the contents of the variables bs and err. But you are right, the return values are named and we don't need to use the names. I reverted that change

2021-06-17 16:08 UTC, ostcar commented
I mad a mess and my github skills are not good enough to fix it. I close this PR here and open a new one. I hope, this will help

2021-06-17 16:08 UTC, closed without merging