Projector.service user slide
OpenSlides/openslides-autoupdate-service pull request #223
Opened 2021-06-09 10:15 UTC by r-peschke

This PR is based on PR https://github.com/OpenSlides/openslides-autoupdate-service/pull/206 Projector Service for agenda_item_list

2021-06-10 04:56 UTC, ostcar commented
Please have a look to my comments in #206 and make a first review by yourself. Please request my review afterwards

2021-06-11 13:42 UTC, ostcar requested changes
Two open questions:
* Errors for the client
* title information

2021-06-25 11:00 UTC, ostcar requested changes

2021-06-25 11:00 UTC, ostcar commented on internal/projector/slide/user.go
> +		responseValue, err := json.Marshal(map[string]interface{}{"user": user.GetUserRepresentation(p7on.MeetingID)})
I don't like this. I would propose that you define a struct:
```go
out := struct{
  User string `json:"user"`
}{
  user.GetUserRepresentation(p7on.MeetingID),
}
responseValue, err := json.Marshal(out)
```

I know this is more to write, but easier to read.

But if makes you happy, you could tolerate your version at this place.

2021-06-25 15:26 UTC, r-peschke commented on internal/projector/projector.go
> +			return bs, err
Done, missed it in rebasing

2021-06-25 15:49 UTC, r-peschke commented on internal/projector/slide/list_of_speakers.go
> +			User:         user.GetUserRepresentation(meetingID),
Done

2021-06-25 15:53 UTC, r-peschke commented on internal/projector/slide/user.go
> +// newUser gets the user from datastore and return the user as dbUser struct together with keys and error
done

2021-06-25 15:54 UTC, r-peschke commented on internal/projector/slide/user.go
> +// getUserRepresentation returns the meeting-dependent string for the given user
done

2021-06-25 15:58 UTC, r-peschke commented on internal/projector/slide/user.go
> +func (u *dbUser) GetUserStructureLevel(meetingID int) string {
done

2021-06-25 15:59 UTC, r-peschke commented on internal/projector/slide/user.go
> +func (u *dbUser) getUserShortName() string {
Changed to capital letter for export

2021-06-25 16:03 UTC, r-peschke commented on internal/projector/slide/user.go
> +		responseValue, err := json.Marshal(map[string]interface{}{"user": user.GetUserRepresentation(p7on.MeetingID)})
changed

2021-06-27 05:23 UTC, ostcar approved these changes
Only two proposals. If you like, you can merge this

2021-06-27 05:23 UTC, ostcar commented on internal/projector/slide/user.go
> +func (u *dbUser) UserRepresentation(meetingID int) string {
Only a proposal:

I would have written the function in this way:

```go
name := u.UserShortName()
level := u.UserStructureLevel(meetingID)
if level == "" {
  return name
}
return fmt.Sprintf("%s (%s)", name, level)
```

It does not seem to be necessary to create a slice and join it at the end.

2021-06-27 05:23 UTC, ostcar commented on internal/projector/slide/user.go
> +		level = u.DefaultLevel
Only a proposal:

It is not unusual in go to have more then one return statement in a function. The rule from other languages, that there should only be one return statement at the end of a function does not apply to go. It solved the problem with the `defer` statement.

With this in mind, I would have wrote this function like this:

```go
if u.Level == "" {
  return u.DefaultLevel
}
return u.Level
```

Also: The attribute `meetingID` is not used in this function. Can it be removed? If not, maybe add a comment why it is necessary (for example to satisfy an interface?

2021-06-28 08:25 UTC, r-peschke commented on internal/projector/slide/user.go
> +func (u *dbUser) UserRepresentation(meetingID int) string {
Done, this is really better

2021-06-28 09:39 UTC, merged