Remove agenda from naming GetTitleInformation registering and calling
OpenSlides/openslides-autoupdate-service pull request #231
Opened 2021-06-23 12:07 UTC by r-peschke

Feel free to change the names on renaming, only the GetTitleInformation context should be visible in any way. Would be nice to have a common system in naming to identify what is an interface, a type, a function, getting a function etc. That is really difficult to distinguish.

2021-06-23 16:22 UTC, ostcar requested changes
Please chance the first comment and the second, if you like.

2021-06-23 16:22 UTC, ostcar commented on internal/projector/slide/agenda.go
> +		options.OnlyMainItems = false // Default value
This is not necessary. Go sets a bool variable to false automatically: https://dave.cheney.net/2013/01/19/what-is-the-zero-value-and-why-is-it-useful

2021-06-23 16:22 UTC, ostcar commented on internal/projector/slides.go
> +type GetTitleInformationType func(ctx context.Context, fetch *datastore.Fetcher, fqid string, itemNumber string) (json.RawMessage, error)
I don't like this name. The a name `FooberFunc` is something used often in go. For example here in the http-lib: https://golang.org/src/net/http/server.go?s=64103:64150#L2055

I would like that this type has the same name as the interface (currently `Titler`) and the sufix `Func`.

2021-06-24 09:47 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +		options.OnlyMainItems = false // Default value
removed it. I wrote it, to set the value explicitly, because I thought about what would be the best default value and the way to set it.

2021-06-24 09:50 UTC, r-peschke commented
> Please chance the first comment and the second, if you like.

Deleted the first comment

2021-06-24 10:01 UTC, r-peschke commented on internal/projector/slides.go
> +type GetTitleInformationType func(ctx context.Context, fetch *datastore.Fetcher, fqid string, itemNumber string) (json.RawMessage, error)
done

2021-06-24 10:46 UTC, ostcar commented
Please Ping when you pushed your changes.

2021-06-24 12:16 UTC, merged