Projector.service: Topic slider
OpenSlides/openslides-autoupdate-service pull request #236
Opened 2021-06-29 17:54 UTC by r-peschke

2021-06-29 18:27 UTC, ostcar requested changes

2021-06-29 18:27 UTC, ostcar commented on internal/projector/slide/topic.go
> +		} else {
You can remove the else block.

Go sets the variable "itemNumber" to an empty string. So the else block is a noop

2021-06-29 18:27 UTC, ostcar commented on internal/projector/slide/topic.go
> +			itemNumber = fetch.String(ctx, fmt.Sprintf("agenda_item/%d/item_number", topic.AgendaItemID))
You do not need the fmt.Sprintf here. You can just call:

```go
fetch.String(ctx, "agenda_item/%d/item_number", topic.AgendaItemID)
```

2021-06-30 07:13 UTC, r-peschke commented on internal/projector/slide/topic.go
> +		} else {
done

2021-06-30 07:21 UTC, r-peschke commented on internal/projector/slide/topic.go
> +			itemNumber = fetch.String(ctx, fmt.Sprintf("agenda_item/%d/item_number", topic.AgendaItemID))
done

2021-06-30 10:49 UTC, ostcar approved these changes

2021-06-30 10:49 UTC, merged