Projector.service assignment slider
OpenSlides/openslides-autoupdate-service pull request #240
Opened 2021-07-01 16:41 UTC by r-peschke

2021-07-02 06:38 UTC, ostcar commented
@r-peschke I rebased the PR on master and now there are no changes left. Can you check if this is correct? Maybe I merged all you changes by mergin #238? If so, can we close this here?

2021-07-02 08:11 UTC, r-peschke commented
> @r-peschke I rebased the PR on master and now there are no changes left. Can you check if this is correct? Maybe I merged all you changes by mergin #238? If so, can we close this here?
There is a new commit with the changes pushed to this PR.

2021-07-02 18:21 UTC, ostcar requested changes
Only one small change. Then you can merge this.

2021-07-02 18:21 UTC, ostcar commented on internal/projector/slide/assignment.go
> +	CandidateIds         []int  `json:"candidate_ids"`
The `D` in `Ids` should be a capital letter: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

2021-07-05 09:49 UTC, r-peschke commented on internal/projector/slide/assignment.go
> +	CandidateIds         []int  `json:"candidate_ids"`
Done

2021-07-05 10:18 UTC, merged