Projector.service:slider CurrentSpeakerChyron and error fixes regardi…
OpenSlides/openslides-autoupdate-service pull request #246
Opened 2021-07-06 07:16 UTC by r-peschke

…ng slider choice collection/type

2021-07-06 18:17 UTC, ostcar requested changes

2021-07-06 18:17 UTC, ostcar commented on internal/projector/projector.go
> +// Only collection meeting from ContentObjectID can be used with type
Could you add a dot at the end of the docstring? Is it possible, that a word is missing in the sentence? (Or is my english not good enough to understand it?)

2021-07-06 18:17 UTC, ostcar commented on internal/projector/slide/list_of_speakers.go
> +// get_losID determines the losID and first current_projection of the reference_projector
Please change the first word of this docstring to `getLostID`. Please also add a dot at the end.

Maybe the function should be called getLOSID, since LOS is a acronym (https://github.com/golang/go/wiki/CodeReviewComments#initialisms). But maybe we should do an exception here, since the all-caps-word looks strange.

2021-07-06 18:17 UTC, ostcar commented on internal/projector/slide/list_of_speakers.go
> +		return losID, referenceProjectorID, fmt.Errorf("invalid Content_objectID %s. Expected a meeting-objectID", ContentObjectID)
Please either use `conent_object_id` or `ContentObjectID` in the error messages. Also in line 186.

2021-07-06 18:17 UTC, ostcar commented on internal/projector/slide/list_of_speakers.go
> +			break
What happens if all losIDs are 0? The function will return 0. Maybe you should either return an error or document this behavior in the docstring.

2021-07-06 18:17 UTC, ostcar commented on internal/projector/slide/list_of_speakers.go
> +		return shortName, structureLevel, fmt.Errorf("loading list of speakers: %w", err)
Please return zero values for the first and second return argument, if the last one is an error. The same at the other places in this function.

2021-07-06 18:17 UTC, ostcar commented on internal/projector/slide/list_of_speakers.go
> +		meetingID, _ := strconv.Atoi(strings.Split(p7on.ContentObjectID, "/")[1])
Maybe chack the error? I know this should always be an int, but maybe it is still a good style to check the error

2021-07-08 07:18 UTC, r-peschke commented on internal/projector/projector.go
> +// Only collection meeting from ContentObjectID can be used with type
done

2021-07-08 07:22 UTC, r-peschke commented on internal/projector/slide/list_of_speakers.go
> +// get_losID determines the losID and first current_projection of the reference_projector
done (changed the name in docstring to getLosID and added a dot)

2021-07-08 07:28 UTC, r-peschke commented on internal/projector/slide/list_of_speakers.go
> +			break
0 is a valid return value for losID and it is no error.

2021-07-08 08:11 UTC, r-peschke commented on internal/projector/slide/list_of_speakers.go
> +		return shortName, structureLevel, fmt.Errorf("loading list of speakers: %w", err)
done

2021-07-08 08:13 UTC, r-peschke commented on internal/projector/slide/list_of_speakers.go
> +		return losID, referenceProjectorID, fmt.Errorf("invalid Content_objectID %s. Expected a meeting-objectID", ContentObjectID)
done

2021-07-08 08:15 UTC, r-peschke commented on internal/projector/slide/list_of_speakers.go
> +		meetingID, _ := strconv.Atoi(strings.Split(p7on.ContentObjectID, "/")[1])
done

2021-07-09 17:49 UTC, ostcar approved these changes

2021-07-09 17:51 UTC, merged