Projector.service sort agenda_item_list on child base
OpenSlides/openslides-autoupdate-service pull request #247
Opened 2021-07-06 13:59 UTC by r-peschke

2021-07-06 18:01 UTC, ostcar requested changes

2021-07-06 18:01 UTC, ostcar commented on internal/projector/slide/agenda.go
> +func getFlatTree(allAgendaItems []outAgendaItem) []outAgendaItem {
First, I did not understand why you sorted the item-list before passing it to this function. Maybe add a docstring that says, that the given list has be sorted by weight.

Or (even better) move the sort-code inside the getFlatTree function, so a caller can not forget to sort the list.

2021-07-08 08:27 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +		sort.SliceStable(allAgendaItems, func(i, j int) bool {
done

2021-07-08 09:46 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +	var buildTree func(itemIDS []int, depth int)
That's what I thought, too. But it doesn't work, because of the recursion. see also in [openslides3](https://github.com/OpenSlides/openslides3-autoupdate-service/blob/0c7fc3c7caf70b974e721f072ba569ce4d762593/internal/apps/agenda/projector.go#L108)

2021-07-08 10:31 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +	allItemMap := make(map[int]outAgendaItem)
done. Everything in the AgendaItem-list is now done with pointers.

2021-07-08 10:52 UTC, r-peschke commented on internal/projector/slide/agenda.go
> +func getFlatTree(allAgendaItems []outAgendaItem) []outAgendaItem {
Wrote a docstring for the getFlatTree function.
I prefer this way for following the principle of separation of concerns: Preorder sorting and creating the output data

2021-07-09 17:46 UTC, ostcar approved these changes

2021-07-09 17:48 UTC, merged