Projector.service Implement motion_block slider
OpenSlides/openslides-autoupdate-service pull request #276
Opened 2021-07-22 18:39 UTC by r-peschke

2021-07-24 05:32 UTC, ostcar requested changes

2021-07-24 05:32 UTC, ostcar commented on internal/projector/projector.go
> +// GetProjection as convenience function reading projections
Why do you need this function? I can not find any place (expect the tests) where it is used.

If it is not used, then please remove this function and add it again, when/if you need it

2021-07-24 05:33 UTC, ostcar commented
Only one comment. The rest is ok and can be merged.

2021-07-26 11:19 UTC, r-peschke commented on internal/projector/projector.go
> +// GetProjection as convenience function reading projections
removed

2021-07-26 11:20 UTC, merged