Update the readme
OpenSlides/openslides-autoupdate-service pull request #748
Opened 2023-08-09 13:29 UTC by ostcar

Fixes #745

2023-08-15 07:51 UTC, jsangmeister requested changes
Sorry for the nitpicking :)

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +host.
```suggestion
service, postgres and redis, for example with the docker argument `--network
host`.
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +The autoupdate services saves, how many connections each user currently open.
```suggestion
The autoupdate services saves how many connections are currently open to each user.
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +The save-interval can be defined with the environment variable
```suggestion
The save interval can be defined with the environment variable
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +METRIC_SAVE_INTERVAL. The default is 5 minutes.
```suggestion
`METRIC_SAVE_INTERVAL`. The default is 5 minutes.
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +The values are saved for each instance of the autoupdate-service. So it is
```suggestion
The values are saved for each instance of the autoupdate service. So it is
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +possible to access all open connection for every autoupdate-service-instance in
```suggestion
possible to access all open connection for every instance of the autoupdate service in
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +`curl "localhost:9012/service/autoupdate/connection_count`
```suggestion
`curl "localhost:9012/service/autoupdate/connection_count"`
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +It returns a json-dictonary like this:
```suggestion
It returns a JSON dictonary like this:
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +The key is a user ID and the value amount of currently open connections. User-ID
```suggestion
The key is a user ID and the value is the amount of currently open connections. User ID
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +connections, the user with the id 1 has 4 open connections and the user with the
```suggestion
connections, the user with the ID 1 has 4 open connections and the user with the
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +Users can only access this page, if they have the organization management level
```suggestion
Users can only access this page if they have the organization management level
```
Which organization management level? I guess `can_manage_organization`?

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +The autoupdate-service logs some metric values. The interval can be set with the
```suggestion
The autoupdate service logs some metric values. The interval can be set with the
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +environment varialbe METRIC_INTERVAL.
```suggestion
environment variable `METRIC_INTERVAL`.
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +  anonymous users from all autoupdate-instances.
```suggestion
  anonymous users from all autoupdate instances.
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +  connected or where connection since the start of the autoupdate-service.
```suggestion
  connected or were connected since the autoupdate service was started.
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +* `connected_users_total_local`: Same as connected_users_total but only for this
```suggestion
* `connected_users_total_local`: Same as `connected_users_total`, but only for this
```

2023-08-15 07:51 UTC, jsangmeister commented on README.md
> +instance. one open connection of this instance.
```suggestion
instance.
```

2023-08-16 07:21 UTC, ostcar commented
@jsangmeister could you open a new PR that I can merge instead of this?

2023-08-22 09:45 UTC, jsangmeister commented
@ostcar I just applied all the changes here. From my side, it can be merged now, if you have no further comments.

2023-08-22 14:36 UTC, merged