Build start_line_number into motion slide
OpenSlides/openslides-autoupdate-service pull request #799
Opened 2023-11-16 16:36 UTC by luisa-beerboom

Closes #798

2023-11-16 16:49 UTC, rrenkert approved these changes

2023-11-17 06:46 UTC, ostcar approved these changes

2023-11-17 07:26 UTC, emanuelschuetze requested changes
2 (client) errors:
- amendment slide (with custom start line number in main motion) -> shows wrong line numbers 
- main motion slide with custom start line number AND change recommendation shows blank slide and client error:  "Error: Inconsistency or invalid call of this function detected (from)"

2023-11-17 08:08 UTC, bastianjoel commented on internal/projector/slide/motion_test.go
>                      "text":"<p>Lead Motion Text HTML</p>"
```suggestion
                    "text":"<p>Lead Motion Text HTML</p>",
```

2023-11-17 11:00 UTC, emanuelschuetze approved these changes

2023-11-17 11:00 UTC, merged