Enhance motion fields
OpenSlides/openslides-autoupdate-service pull request #844
Opened 2024-02-12 13:27 UTC by jsangmeister

needed for https://github.com/OpenSlides/openslides-client/pull/3164

2024-02-12 13:39 UTC, jsangmeister commented
Interestingly, the new feature works even without these changes. Does the autoupdate service simply pipe through unkown collections?

2024-02-14 10:37 UTC, bastianjoel commented
So a motion with state restriction `is_submitter` should be visible to a user if the user is an editor? Is this correct? @emanuelschuetze

2024-02-14 13:26 UTC, jsangmeister commented
> So a motion with state restriction `is_submitter` should be visible to a user if the user is an editor? Is this correct? @emanuelschuetze

talked with @emanuelschuetze: No, there should be no changes to the visibility of a motion for editors/working group speakers

2024-02-14 13:56 UTC, ostcar requested changes
This should probably be a draft until the changes to meta was merged into its main branch.

If there is a PR (not a draft PR) that looks good, then I think, that I should merge it.

2024-02-14 13:56 UTC, ostcar commented on internal/restrict/collection/motion_editor.go
> +func (e MotionEditor) Name() string {
Could you change the `e` parameter to `m`. I always use the first letter of the collection

2024-02-14 13:56 UTC, ostcar commented on internal/restrict/collection/motion_editor.go
> +	case "B":
There is no collection mode `B`. Please remove this case

2024-02-14 13:56 UTC, ostcar commented on internal/restrict/collection/motion_working_group_speaker.go
> +	case "B":
There is no collection mode `B`. Please remove this case

2024-02-15 06:55 UTC, ostcar approved these changes

2024-02-15 06:55 UTC, emanuelschuetze submitted a review, later dismissed
I cannot test this PR (together with client and backend). There is an error after trying to login with a normal user (superadmin works)!

```
autoupdate-1        | 2024/02/15 06:52:33 http: panic serving 172.21.0.14:36924: runtime error: invalid memory address or nil pointer dereference
```

2024-02-15 07:03 UTC, ostcar commented
> I cannot test this PR (together with client and backend). There is an error after trying to login with a normal user (superadmin works)!
> 
> ```
> autoupdate-1        | 2024/02/15 06:52:33 http: panic serving 172.21.0.14:36924: runtime error: invalid memory address or nil pointer dereference
> ```

Are you sure, that this is the only error message? When there is a panic, there should be a lot of lines in the error log

2024-02-15 08:24 UTC, bastianjoel commented
I cannot replicate this

2024-02-15 08:48 UTC, jsangmeister commented
> I cannot replicate this

Me neither

2024-02-15 09:35 UTC, merged