Split connection count metirc for longpolling
OpenSlides/openslides-autoupdate-service pull request #929
Opened 2024-05-01 07:17 UTC by ostcar

This PR changes the metric values. See the changes in the README.

2024-05-02 13:31 UTC, peb-adr requested changes

2024-05-02 13:31 UTC, peb-adr commented on internal/http/http.go
> +		connectionCount[1] = newConnectionCount(ctx, redisConnection, saveIntercal, "connections_logpolling")
typo 'logpolling'.
Will fixing it here also fix it in the README.md?

2024-05-02 14:59 UTC, peb-adr approved these changes

2024-05-02 15:02 UTC, merged

2024-05-14 07:01 UTC, bastianjoel commented
This was a breaking change for the api used by the client which caused a bug. Maybe assign someone who works on the client next time.

2024-05-15 13:33 UTC, ostcar commented
I am sorry. I only though about the graphana metric. I was not aware at the moment, that the values are also used by the client.